name: Georepublic
permalink: /blog/:year/:title
relative_permalinks: false
excerpt_separator: "<!-- more -->"
markdown: rdiscount

paginate: 5
paginate_path: "blog/page/:num"

# Prose settings
prose:
  rooturl: 'blog/_posts'
  siteurl: "http://beta.georepublic.info"
  relativeLinks: 'http://beta.georepublic.info/links.jsonp'
  media: "media"

  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"

      - name: "title"
        field:
          label: "Title"
          element: "text"

      - name: "date"
        field:
          label: "Date"
          element: "text"
          placeholder: "YYYY-MM-DD hh:mm:ss"

      - name: "author"
        field:
          label: "Author"
          element: "text"
          value: "Team Georepublic"

      - name: "language"
        field:
          label: "Language"
          element: "select"
          options: 
            - name: "English"
              value: "en"
            - name: "日本語"
              value: "ja"
            - name: "Deutsch"
              value: "de"

      - name: "tags"
        field:
          label: "Tags"
          element: "multiselect"
          options: ["News", "Technology", "Community", "FOSS4G", "Release"]
          alterable: true

      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: true

      - name: "comments"
        field:
          label: "Comments"
          element: "checkbox"
          value: true
